apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: mike-admission-controller
webhooks:
- name: mike-admission-controller.mike-admission-controller.svc
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: mike-admission-controller
      name: mike-admission-controller
      path: "/"
    # cat ca.crt | base64  
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQWFvQ0NRQ0FoVFk1WTR1ZTBqQU5CZ2txaGtpRzl3MEJBUXNGQURBak1TRXdId1lEVlFRRERCaEoKYldGblpTQldZV3hwWkdGMGFXOXVJRmRsWW1odmIyc3dIaGNOTWpNd05qRXlNVGcxTkRFeFdoY05Nak13TnpFeQpNVGcxTkRFeFdqQWpNU0V3SHdZRFZRUUREQmhKYldGblpTQldZV3hwWkdGMGFXOXVJRmRsWW1odmIyc3dnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRE44SVdkb1FaOEF0NnJLV1Q1eFpHc1NSL2wKTW94YlhUbDdvcGl1WlE2WVJWNFZWRVgvc1dRQ2NQNkJBL0VYUGlxaHI1UXh1cHlzSGE0Z0FlWmVLYzNWcDlhbwpoZkZ3K1RPV3Z1cmJLdVdmVW9sZHRyWFJYZXI5Zlg0NEdLbjdUa2VhZzc1b1Q4cHg2TWFvYmg1ZjdJT3k5NmhUClVIek1LajZSaDdUM1BFQm13U1RUdWZDSXR3dVJKR0V3RVMyL2w2cG9UUGJ2eTVUZ2NnZVBaeG5YYTVtdllObXUKd2srcThwMkZaNzUvWUpPV3ljY3JNSnovbjFNdGNraDhPY2pwaFpvajdVM1A3dkZUTXpjSk1CVkZVTk1wWmhBUQozWnlqclRyYzBJSnIyS3JXTFZpZGNuQ2NaZU9rcVY0ejNkN3lhdVRUZXFNM2tKRWREWnZXR3pQSXYwOVZBZ01CCkFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSjQrUk5CQWNwRWF1cWJwbnBTcE44VzNNU3llQUUzYnFxSUwKa3JiY2JWUm1meGd3TElRR2NZZ3lMREtDbVNlSHBLWUVjK1hwTDlOWUVhenJXcUhQdlBVQitPalVNYWR4WGF5UwpwZkZtNzNuUyt0bWtyN0xZRWlGb2tOdTRMZDNsaHc0K0d6eHhodTNYRWJGSWJhSDhEdlJiaDRNSUU1a2FzRjRqCmtGYWg5cEZLK3ZqV3Z6Qm5BK09nRmIxZEJrYjh2VUJ2ZzIzWldUS25aMkdRNDlNYTIzOWRNK1JzWE9CbXBGYmQKTExZWlFENXp3TTBlblgwUEVwbGZPZDZmRUh2ZUkvWFk3Q3RUTzJzaFhQNkdMOUowNnVjMzdyRnRZZW90SGhKTQp4Q3Q3aEZWU0l6RWNyQmNUN1pOWHlpSkpORlBRVlM4bXQ3THE1TFRpN1pCb21IWGF6VlE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  admissionReviewVersions: ["v1"]
  sideEffects: None